# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.14.2
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
github_check_license: false
github_ci_extra_env: {}
github_enable_codecov: false
github_enable_makepot: false
github_enable_stale_action: true
github_enforce_dev_status_compatibility: false
include_wkhtmltopdf: true
odoo_version: 10.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups: []
repo_description: "This project aim to deal with modules related to manage document\
    \ printing and sending in a generic way. You'll find modules that:\n\n    - Interface\
    \ Odoo with Pingen (https://www.pingen.com/en)\n    - Add an printing queue\n\
    \    - Allow to choose printer"
repo_name: Report - Printing and Sending
repo_slug: report-print-send
repo_website: https://github.com/OCA/report-print-send
travis_apt_packages: []
travis_apt_sources: []

